#!/usr/bin/env bash
# SMB-safe Gradle wrapper for the Quest subproject.
#
# The checkout lives on an SMB share, where three Gradle behaviours break:
#   1. lock files in the project cache dir throw on network mounts,
#   2. file-system watching is unreliable over SMB,
#   3. :app:packageDebug fails late ("Unable to delete directory …
#      packageDebug/tmp") when the build directory is on the share.
# This wrapper keeps Gradle state (user home, project cache, and every
# project's build directory) on the local disk and copies finished APKs back
# into the tree so paths in the README/audits stay true.
#
# Usage, from quest/:  scripts/gradle-local.sh testDebugUnitTest assembleDebug
# Dev tooling build:   scripts/gradle-local.sh -PdevTools assembleDebug
set -euo pipefail

QUEST_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCAL_ROOT="${OPENPANEL_QUEST_LOCAL_ROOT:-${TMPDIR:-/tmp}/openpanel-quest-gradle}"
BUILD_ROOT="$LOCAL_ROOT/build"
INIT_SCRIPT="$LOCAL_ROOT/redirect-build-dir.init.gradle"

if [[ -z "${JAVA_HOME:-}" ]]; then
  if [[ -x /usr/libexec/java_home ]]; then
    JAVA_HOME="$(/usr/libexec/java_home -v 21)"
  else
    echo "OpenPanel Quest requires JDK 21. Set JAVA_HOME." >&2
    exit 1
  fi
fi
if [[ "$("$JAVA_HOME/bin/java" -version 2>&1)" != *'version "21.'* ]]; then
  echo "OpenPanel Quest requires JDK 21; JAVA_HOME points elsewhere." >&2
  exit 1
fi
export JAVA_HOME

if [[ -z "${ANDROID_HOME:-}" && -d "$HOME/Library/Android/sdk" ]]; then
  export ANDROID_HOME="$HOME/Library/Android/sdk"
fi

# ~/.gradle already lives on the local disk and holds the warm dependency
# cache; only project cache, build dirs, and fs-watching are SMB problems.
if [[ -n "${GRADLE_USER_HOME:-}" ]]; then export GRADLE_USER_HOME; fi
mkdir -p "$BUILD_ROOT"

cat > "$INIT_SCRIPT" << EOF
// Generated by scripts/gradle-local.sh — keeps build output off the SMB share.
gradle.allprojects { project ->
  def key = project.path == ':' ? 'root' : project.path.substring(1).replace(':', '_')
  project.layout.buildDirectory.set(new File('$BUILD_ROOT', key))
}
EOF

"$QUEST_ROOT/gradlew" \
  -p "$QUEST_ROOT" \
  --project-cache-dir "$LOCAL_ROOT/project-cache" \
  --no-watch-fs \
  --init-script "$INIT_SCRIPT" \
  "$@"

# Copy finished APKs back into the tree so documented output paths hold.
for variant in debug release; do
  local_apk_dir="$BUILD_ROOT/app/outputs/apk/$variant"
  if [[ -d "$local_apk_dir" ]]; then
    dest="$QUEST_ROOT/app/build/outputs/apk/$variant"
    mkdir -p "$dest"
    find "$local_apk_dir" -name "*.apk" -newer "$INIT_SCRIPT" -exec cp {} "$dest/" \; 2>/dev/null || true
  fi
done
