// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.20'
        classpath 'com.google.gms:google-services:4.4.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply from: "variables.gradle"

def openPanelLocalBuildRoot = System.getenv('OPENPANEL_GRADLE_BUILD_ROOT')
if (openPanelLocalBuildRoot) {
    allprojects { targetProject ->
        targetProject.layout.buildDirectory.set(file("${openPanelLocalBuildRoot}/${targetProject.name}"))
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
        maven {
            url 'https://jitpack.io'
            content {
                includeGroup 'com.github.marain87'
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
